[input]
;iFile=[1:11]
iFile=1:size(tmp,1)
Thr=85

;Threshold to remove low OCT signal
IMcropRg=30:480
RgStr=[71.2 116.8]
RgFlow=[-5 25]
RgFlow_ed=[80 90]
DispCoef=1

[action]
do_PhComp=1
;toggle phase compensation
do_medianshift=1
;toggle median shift in phase compensation
do_reg=1
;toggle Inter-Frame registration (for motion removal)
Nsub=10
Colshift=0
;parameters for inter-frame registration

use_autoRg=1
;toggle auto dynamic range
useref=0
;toggle use reference recorded in rawdata
useDVV=0

saveDicom=1
show_img=1

[norm]
iFile=1:size(tmp,1)
;iFile=8
listNorm={'Flow_ed'}
RgFlowNM=[-13713.20 41178.67]
normFactor=0.62
use_autoFlowRg=1
use_uniformNorm=1
;use the same Norm Coef for every input.
do_medianflow=0
medianflowfactor=1.0
;toggle median flow shift

[seg]
iFile=1:size(tmp,1)
;iFile=8
nV=4
;set nV=0 to use automatic nV from filename.

ListSeg={'Flow_edNM'}
;ListSeg={'C1_NM_Flow_ed','flow_reg'}

do_loadSeg=1
do_showSeg=0
do_testSeg=0
do_Blend_Flatten=0
do_Blend=0
do_Flow_Flatten=1
do_Flow_MskFlatten=0

do_LegacyProj=1
do_MultiDepth=0
use_autoRg_Seg=0

do_MultiLayerProj=0
do_TailFilter=1
do_Flow_Flatten_Tailfilter=1

RgStr=[80 128]
RgFlow=[0 1]
RgFlow_ed=[-10 22]

nRB=1
nZshift=0
nZthick=350
BandLines=[45,81,150]
WinSize=70
thrsh_ratio=0.85
medfiltsize=[5 5]
gaussfiltsize=[19 19]

cutA=0
cutB=0
grayRg=[0.25 0.98]
cmapRg=[0.05 0.75]
grayRgMulti=[0.25 0.98]
MaxAve=3

[proj]
mode=fixed
RemoveMotion=1
BandLines=[0.04 0.2 0.45 0.95]
RgDyn=[0 1.646]
RgGray=[20 99.9]
RgGrayFixed=[0.3282 0.9000; 0.3653 0.9308; 0.4690 0.7791]
RgGrayFixedTR=[0.1742 0.5620; 0.1281 0.4733; 0.1530 0.3583]
